import { LocalDB } from "@/lib/local-db"
import { type NextRequest, NextResponse } from "next/server"

export async function GET(req: NextRequest) {
  try {
    const db = new LocalDB()
    const user = db.getCurrentUser()

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { searchParams } = new URL(req.url)
    const contentId = searchParams.get("id")
    const format = searchParams.get("format") || "json"

    if (!contentId) {
      return NextResponse.json({ error: "Content ID is required" }, { status: 400 })
    }

    const content = db.getGeneratedContentById(contentId, user.id)

    if (!content) {
      return NextResponse.json({ error: "Content not found" }, { status: 404 })
    }

    let downloadContent = ""
    let filename = ""
    let contentType = "text/plain"

    if (format === "json") {
      downloadContent = JSON.stringify(content, null, 2)
      filename = `red-rose-ai-content-${contentId}.json`
      contentType = "application/json"
    } else if (content.type === "text") {
      downloadContent = `# Generated by Red Rose AI - 100% FREE
# Content ID: ${contentId}
# Generated: ${content.created_at}
# Prompt: ${content.prompt}

${content.content || "No text content available"}

---
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!`
      filename = `red-rose-ai-text-${contentId}.txt`
    } else if (content.type === "code") {
      downloadContent = `// Generated by Red Rose AI - 100% FREE
// Content ID: ${contentId}
// Generated: ${content.created_at}
// Prompt: ${content.prompt}

${content.content || "No code content available"}

/*
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!
*/`
      filename = `red-rose-ai-code-${contentId}.js`
    } else if (content.type === "image") {
      // For images, return the metadata and description
      downloadContent = `# Red Rose AI - FREE Image Generation
# Content ID: ${contentId}
# Generated: ${content.created_at}
# Prompt: ${content.prompt}

${content.content || "No description available"}

---
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!`
      filename = `red-rose-ai-image-${contentId}.txt`
    }

    // Return file as download
    return new NextResponse(downloadContent, {
      headers: {
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${filename}"`,
        "X-Generated-By": "Red Rose AI - 100% FREE",
      },
    })
  } catch (error) {
    console.error("Download content error:", error)
    return NextResponse.json({ error: "Failed to download content" }, { status: 500 })
  }
}
